### ISSUE TITLE
Installing Issue

### ISSUE THREAD

**Issue by Pythnlearner** [pdff/Hackintosh-HP-Elitebook840G7#5]
[HP](url) 840 G7

Installation stuck.  Catalina + EFI 1.1 updated
![boot stuck](https://user-images.githubusercontent.com/66311873/143206654-739936b1-d032-448f-b4fa-182f4717bee9.jpg)

**Comment by pdff** [comment]
Go for the 1.0 folder when installing fresh and after update to bigsur/monterey go for the 1.1 folder :)

**Comment by pdff** [comment]
If you want my master (latest folder with 0.7.6 contact me personally through email.

**Comment by Pythnlearner** [comment]
Thank you sir, 

I have mailed you through my Gmail.

**Comment by Pythnlearner** [comment]
> Go for the 1.0 folder when installing fresh and after update to bigsur/monterey go for the 1.1 folder :)

I have tried catelina with 1.0 folder also got the same issue

**Comment by Pythnlearner** [comment]
Ok please  help me on this. i will try your latest EFI.
